name: Go Build

on:
  push:
    branches:
      - main 

jobs:
  build:
    needs: [msys2-ucrt64]
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.1  

    - name: Build
      run: go build ./...

  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install dlib headers
        run: pacman -S --noconfirm mingw-w64-x86_64-dlib-devel
      - name: Install build dependencies
        run: pacman -S --noconfirm git mingw-w64-ucrt-x86_64-gcc
