name: Go Build

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: windows-latest
    needs: [msys2-ucrt64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go and Build Dependencies
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.1  
        gcc: mingw64

    - name: Build
      run: go build

  msys2-ucrt64:
    runs-on: windows-latest
    steps:
      - name: Install build dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc
