name: Go Build

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: windows-latest
    needs: [setup]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.1  

    - name: Build
      run: go build ./...

  setup:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dlib in Git Bash
        run: |
          git config --global core.autocrlf false
          pacman --noconfirm -S mingw-w64-x86_64-dlib
