name: MSYS2
on: [ release, push ]

jobs:
  msys2-ucrt64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-dlib mingw-w64-x86_64-lapack mingw-w64-x86_64-cblas
          path-type: inherit

      - name: Set up Go and Build Dependencies
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2

      - name: Build
        run: msys2 -c 'go build' -o server
      
      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: built-program
          path: server.exe
