name: My-GithubActions-Trying

on:
  push:
    branches:
      - master
jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Message
      run : echo "Hello world"
      
